[package]
name = "rust-c-practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

links = "foo"
build = "build.rs"

[dependencies]

[build-dependencies]
gcc = "0.3"